/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2019-08-25 16:28:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class serviceCenter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <script type=\"text/javascript\" async=\"\" src=\"https://www.google-analytics.com/analytics.js\" nonce=\"\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/2e0fe97ffd4425e93ec036ab0a2f17bd.js?conditionId0=3241080\" crossorigin=\"anonymous\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/1cb1e5723a12e45c1f52a2e2ad9821d3.js?conditionId0=1188581\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/21a0949ecd20c57a834ab43dfcfecbc9.js\" crossorigin=\"anonymous\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/742b1f7c20fad47d5a440466f1265000.js\" crossorigin=\"anonymous\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/477fc7cf7e5ceaf7a4c6ba38fd8fad65.js?conditionId0=4836836\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/fab8ea4e652a6548d13317c8f4b8bd78.js?conditionId0=422975\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/dd6797289466fcafceda54ba0fd683a6.js?conditionId0=422975\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/8e18c6ffc5e6a03029d40e13cdd779eb.js?conditionId0=422975\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/bcb41607f75ea330dedec9a4085353b5.js?conditionId0=422975\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/8c024cb0043360c0a183ef86569e5a97.js?conditionId0=422975\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/tagmgmt/codefiles/574f63be35e76260a66d1f463ade4578.js?conditionId0=422975\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" async=\"\" crossorigin=\"anonymous\" src=\"https://www.paypalobjects.com/tagmgmt/codefiles/802b93f0fe41b41869a2e449e704709d.js?conditionId0=378623\"></script>\r\n");
      out.write("    <script async=\"\" src=\"https://www.paypalobjects.com/tagmgmt/bootstrap.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://www.paypalobjects.com/web/res/c54/359e968cf4b91a2096b1cc7bb621b/js/xhr-ads.min.js\"></script>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"apple-mobile-web-app-capable\" content=\"yes\"><meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\"><meta name=\"format-detection\" content=\"telephone=no\"><meta http-equiv=\"generator\" content=\"AM_BX_CY_DM_JH_LZ_MG_ML_MP_NA_NY_PS_RB_RJ_SA_SD_SS_SP_SV_VB_VC_VM\"><meta name=\"description\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"https://www.paypalobjects.com/webstatic/icon/pp144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"https://www.paypalobjects.com/webstatic/icon/pp72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"https://www.paypalobjects.com/webstatic/icon/pp64.png\"><link rel=\"shortcut icon\" sizes=\"196x196\" href=\"https://www.paypalobjects.com/webstatic/icon/pp196.png\"><link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://www.paypalobjects.com/webstatic/icon/favicon.ico\"><link rel=\"icon\" type=\"image/x-icon\" href=\"https://www.paypalobjects.com/webstatic/icon/pp32.png\"><link rel=\"alternate\" hreflang=\"ko-KR\" href=\"https://www.paypal.com/kr/smarthelp/contact-us\"><link rel=\"stylesheet\" href=\"https://www.paypalobjects.com/web/res/17b/cd5bb332bb4330ea2bb85b0e1388b/css/rac/noderac.css\"><link rel=\"stylesheet\" href=\"https://www.paypalobjects.com/web/res/17b/cd5bb332bb4330ea2bb85b0e1388b/css/mpp-header-footer.css\"><link rel=\"stylesheet\" href=\"https://www.paypalobjects.com/web/res/17b/cd5bb332bb4330ea2bb85b0e1388b/css/app.css\"><title>문의하기</title><script src=\"//cdn.jsdelivr.net/npm/mutationobserver-shim/dist/mutationobserver.min.js\" nonce=\"\"></script></head>\r\n");
      out.write("<meta charset=\"urf-8\"/>\r\n");
      out.write("<style>\r\n");
      out.write("    @media ( min-width : 768px) {\r\n");
      out.write("        .navbar-nav.navbar-center {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translatex(-50%);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body data-view-name data-device-layout=\"dedicated\">\r\n");
      out.write("<header>\r\n");
      out.write("    <nav class=\"navbar navbar-transparent navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"navbar-header navbar-dark\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("                    data-target=\".navbar-collapse\">\r\n");
      out.write("                <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("                    class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-collapse collapse\">\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li><a href=\"#\">PayLog</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("                <li><a href=\"#\">개인</a></li>\r\n");
      out.write("                <li><a href=\"#\">고객</a></li>\r\n");
      out.write("                <li><a href=\"#\">구매</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("                <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("<br><br>\r\n");
      out.write("<div class=\"page-main-container\" role=\"main\">\r\n");
      out.write("    <div id=\"refund-alert\" name=\"contact\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"alert-container\"></div>\r\n");
      out.write("    <div class=\"topic-tree-switcher\">\r\n");
      out.write("        <div class=\"topic-tree-browser-container\">\r\n");
      out.write("            <div class=\"contact-search-container\">\r\n");
      out.write("                <div class=\"channel-steering-grid\">\r\n");
      out.write("                    <div class=\"channel-steering-grid-left\">\r\n");
      out.write("                    </div><!--\r\n");
      out.write("<div class=\"channel-steering-grid-middle\"> -->\r\n");
      out.write("                    <div class=\"channel-steering-grid-middle\">\r\n");
      out.write("                        <p class=\"contact-us-header\">PayLog에서 더 신속하게 도움을 드릴 수 있도록 고객님의 문제를 알려주세요.</p>\r\n");
      out.write("                        <div class=\"crawl-intent-topic-container\">\r\n");
      out.write("<span class=\"cw_icon cw_icon-small cw_icon-search-small crawl-intent-search-icon\" aria-hidden=\"true\">\r\n");
      out.write("</span>\r\n");
      out.write("                            <label for=\"crawl-intent-input-text\" class=\"label-crawl-intent-input-text sr-only\">내 문제 검색</label>\r\n");
      out.write("                            <div role=\"combobox\" aria-haspopup=\"listbox\" aria-owns=\"react-autowhatever-1\" aria-expanded=\"false\" class=\"react-autosuggest__container\">\r\n");
      out.write("                                <input type=\"text\" autocomplete=\"off\" aria-autocomplete=\"list\" aria-controls=\"react-autowhatever-1\" class=\"crawl-intent-input\" placeholder=\"내 문제 검색\" maxlength=\"250\" id=\"crawl-intent-input-text\" value=\"\">\r\n");
      out.write("                                <div id=\"react-autowhatever-1\" role=\"listbox\" class=\"react-autosuggest__suggestions-container\"></div></div></div></div><div class=\"channel-steering-grid-right\"></div></div></div><div class=\"channel-steering-grid\"><div class=\"channel-steering-grid-left\"></div>\r\n");
      out.write("            <div class=\"channel-steering-grid-middle\">\r\n");
      out.write("                <h2 class=\"topic-tree-browser-header topic-tree-browser-header__search_tree\">일반적인 문제</h2>\r\n");
      out.write("                <div class=\"topics-list-container\">\r\n");
      out.write("                    <div class=\"topic-list-content\">\r\n");
      out.write("                        <button class=\"topic-item topic-item__search_tree topic-item__hasLabel\" tabindex=\"0\" pa-marked=\"1\">\r\n");
      out.write("                            <div class=\"item-container\">\r\n");
      out.write("                                <div class=\"item-heading\">비밀번호 및 계정 액세스</div>\r\n");
      out.write("                                <div class=\"item-label\">재설정,  계정 잠금 해제,  모르는 청구\r\n");
      out.write("                                </div></div>\r\n");
      out.write("                            <span class=\"GlyphIcon vx_icon vx_icon-arrow-right-small vx_icon-small accordion-icon\" aria-hidden=\"true\"></span></button></div>\r\n");
      out.write("                    <div class=\"topic-list-content\"><button class=\"topic-item topic-item__search_tree topic-item__hasLabel\" tabindex=\"0\" pa-marked=\"1\">\r\n");
      out.write("                        <div class=\"item-container\">\r\n");
      out.write("                            <div class=\"item-heading\">결제</div>\r\n");
      out.write("                            <div class=\"item-label\">취소,  환불,  인출</div></div>\r\n");
      out.write("                        <span class=\"GlyphIcon vx_icon vx_icon-arrow-right-small vx_icon-small accordion-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </button></div><div class=\"topic-list-content\">\r\n");
      out.write("                    <button class=\"topic-item topic-item__search_tree topic-item__hasLabel\" tabindex=\"0\" pa-marked=\"1\">\r\n");
      out.write("                        <div class=\"item-container\">\r\n");
      out.write("                            <div class=\"item-heading\">계정 프로필 및 설정</div>\r\n");
      out.write("                            <div class=\"item-label\">신용카드 또는 직불카드,  은행계좌,  이메일,  전화</div></div>\r\n");
      out.write("                        <span class=\"GlyphIcon vx_icon vx_icon-arrow-right-small vx_icon-small accordion-icon\" aria-hidden=\"true\"></span></button>\r\n");
      out.write("                </div><div class=\"topic-list-content\">\r\n");
      out.write("                    <button class=\"topic-item topic-item__search_tree topic-item__hasLabel\" tabindex=\"0\" pa-marked=\"1\"><div class=\"item-container\"><div class=\"item-heading\">분쟁 및 계정 제한</div>\r\n");
      out.write("                        <div class=\"item-label\">제한,  결제 분쟁,  지불거절</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <span class=\"GlyphIcon vx_icon vx_icon-arrow-right-small vx_icon-small accordion-icon\" aria-hidden=\"true\"></span></button></div>\r\n");
      out.write("                    <div class=\"topic-list-content\">\r\n");
      out.write("                        <button class=\"topic-item topic-item__search_tree topic-item__hasLabel\" tabindex=\"0\" pa-marked=\"1\">\r\n");
      out.write("                            <div class=\"item-container\">\r\n");
      out.write("                                <div class=\"item-heading\">비즈니스 솔루션</div>\r\n");
      out.write("                                <div class=\"item-label\">수수료,  주문,  준비금</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"GlyphIcon vx_icon vx_icon-arrow-right-small vx_icon-small accordion-icon\" aria-hidden=\"true\">\r\n");
      out.write("</span></button></div></div></div>\r\n");
      out.write("            <div class=\"channel-steering-grid-right\">\r\n");
      out.write("            </div></div></div></div><div></div><div></div>\r\n");
      out.write("    <div><div class=\"col-xs-0 col-sm-1 col-md-1 col-lg-1\"></div>\r\n");
      out.write("        <div class=\"contact-options col-xs-12 col-sm-10 col-md-10 col-lg-10\">\r\n");
      out.write("            <div class=\"call-header\">기타 문의 방법</div>\r\n");
      out.write("            <ul class=\"contact-panels\">\r\n");
      out.write("                <li class=\"contact-option-list-item\">\r\n");
      out.write("                    <div class=\"contact-panel\" id=\"contact-contact-chat-option\">\r\n");
      out.write("                        <div class=\"vx_btn-link disable-icon-chat\" aria-hidden=\"true\">\r\n");
      out.write("                        </div><div class=\"channel-content\">\r\n");
      out.write("                        <button class=\"btn vx_btn-link disable-contact-link\" tabindex=\"-1\" pa-marked=\"1\">PayLog 상담원과 채팅하기</button>\r\n");
      out.write("                        <div class=\"support-message\">\r\n");
      out.write("                            <span>위 문제 중 하나를 선택하세요.</span>\r\n");
      out.write("                        </div></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li><li class=\"contact-option-list-item\">\r\n");
      out.write("                <div class=\"contact-panel\" id=\"contact-contact-resolution-option\">\r\n");
      out.write("                    <div class=\"vx_btn-link icon-resolution\" aria-hidden=\"true\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"channel-content\">\r\n");
      out.write("                        <button class=\"btn vx_btn-link contact-link\" pa-marked=\"1\">Q&A 센터</button>\r\n");
      out.write("                        <div class=\"support-message\">\r\n");
      out.write("                            <span>거래 문제 등 해결하기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("                <li class=\"contact-option-list-item\">\r\n");
      out.write("                    <div class=\"contact-panel\" id=\"contact-contact-email-option\">\r\n");
      out.write("                        <div class=\"vx_btn-link icon-emailus\" aria-hidden=\"true\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"channel-content\">\r\n");
      out.write("                            <button class=\"btn vx_btn-link contact-link\" pa-marked=\"1\">이메일 보내기</button>\r\n");
      out.write("                            <div class=\"support-message\"><span>로그인이 필요합니다.</span>\r\n");
      out.write("                            </div></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!-- <li class=\"contact-option-list-item\">\r\n");
      out.write("                <div class=\"contact-panel\" id=\"contact-contact-callus-option\">\r\n");
      out.write("                <div class=\"vx_btn-link icon-callus\" aria-hidden=\"true\"></div>\r\n");
      out.write("                <div class=\"channel-content\">\r\n");
      out.write("                <button class=\"btn vx_btn-link contact-link\" pa-marked=\"1\">전화하기</button>\r\n");
      out.write("                <div class=\"support-message\"><span>저희가 도와 드리겠습니다.</span>\r\n");
      out.write("                </div></div></div></li>\r\n");
      out.write("                 -->\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div></div><div></div></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
