/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2019-09-06 05:19:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class qnaRead3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/D:/SpringMVCProject/Springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/8.29home/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/SpringMVCProject/Springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/8.29home/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.1.1.RELEASE.jar", Long.valueOf(1567346765702L));
    _jspx_dependants.put("jar:file:/D:/SpringMVCProject/Springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/8.29home/WEB-INF/lib/spring-security-taglibs-3.1.4.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1366952648000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.1.4.RELEASE.jar", Long.valueOf(1567346787558L));
    _jspx_dependants.put("jar:file:/D:/SpringMVCProject/Springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/8.29home/WEB-INF/lib/spring-webmvc-4.1.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1412094440000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1567346802003L));
    _jspx_dependants.put("jar:file:/D:/SpringMVCProject/Springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/8.29home/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jquery 추가 -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.1.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http:code.jquery.com/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 댓글 작성 추가문  -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .panel-body {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .list-group {\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .panel-title {\r\n");
      out.write("\tdisplay: inline\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .label-info {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget li.list-group-item {\r\n");
      out.write("\tborder-radius: 0;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tborder-top: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget li.list-group-item:hover {\r\n");
      out.write("\tbackground-color: rgba(86, 61, 124, .1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .mic-info {\r\n");
      out.write("\tcolor: #666666;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .action {\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .comment-text {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget .btn-block {\r\n");
      out.write("\tborder-top-left-radius: 0px;\r\n");
      out.write("\tborder-top-right-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: .3em;\r\n");
      out.write("\theight: 1.3em;\r\n");
      out.write("\tz-index: 3;\r\n");
      out.write("\tfont-size: 12px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or:before {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tbackground-color: #5a5a5a;\r\n");
      out.write("\tmargin-top: -.1em;\r\n");
      out.write("\tmargin-left: -.9em;\r\n");
      out.write("\twidth: 1.8em;\r\n");
      out.write("\theight: 1.8em;\r\n");
      out.write("\tline-height: 1.55;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder-radius: 500px;\r\n");
      out.write("\t-webkit-box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\tbox-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\t-webkit-box-sizing: border-box;\r\n");
      out.write("\t-moz-box-sizing: border-box;\r\n");
      out.write("\t-ms-box-sizing: border-box;\r\n");
      out.write("\tbox-sizing: border-box\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or:after {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tcontent: ' ';\r\n");
      out.write("\twidth: .3em;\r\n");
      out.write("\theight: 2.84em;\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0);\r\n");
      out.write("\tborder-top: .6em solid #5a5a5a;\r\n");
      out.write("\tborder-bottom: .6em solid #5a5a5a\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or.or-lg {\r\n");
      out.write("\theight: 1.3em;\r\n");
      out.write("\tfont-size: 16px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or.or-lg:after {\r\n");
      out.write("\theight: 2.85em\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or.or-sm {\r\n");
      out.write("\theight: 1em\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or.or-sm:after {\r\n");
      out.write("\theight: 2.5em\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or.or-xs {\r\n");
      out.write("\theight: .25em\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .or.or-xs:after {\r\n");
      out.write("\theight: 1.84em;\r\n");
      out.write("\tz-index: -1000\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons:after {\r\n");
      out.write("\tcontent: \".\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tvisibility: hidden\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .btn {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder-radius: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .btn:first-child {\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("\tborder-top-left-radius: .25em;\r\n");
      out.write("\tborder-bottom-left-radius: .25em;\r\n");
      out.write("\tpadding-right: 15px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-group-buttons .btn:last-child {\r\n");
      out.write("\tborder-top-right-radius: .25em;\r\n");
      out.write("\tborder-bottom-right-radius: .25em;\r\n");
      out.write("\tpadding-left: 15px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tlistReply(\"1\"); //첫번째 페이지 댓글 목록이 나옴\r\n");
      out.write("\t\t$(\"#btnReply\").click(function() {\r\n");
      out.write("\t\t\treply();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#btnList\").click(function() {\r\n");
      out.write("\t\t\tlocation.href = \"gtQnaList.do\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#btnUpdate\").click(function() {\r\n");
      out.write("\t\t\tlocation.href = \"qnaUpdatePage.do?q_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#btnDelete\").click(function() {\r\n");
      out.write("\t\t\tif (confirm(\"정말 삭제하시겠습니까?\")) {\r\n");
      out.write("\t\t\t\tdocument.form1.action = \"qnaDelete.do\";\r\n");
      out.write("\t\t\t\tdocument.form1.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t/* location.href = \"qnaDelete.do?q_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; */\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction reply() {\r\n");
      out.write("\t\tvar comt_content = $(\"#comt_content\").val(); //댓글내용\r\n");
      out.write("\t\tvar comt_textid = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; //원글 번호\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\"comt_content\" : comt_content,\r\n");
      out.write("\t\t\t\"comt_textid\" : comt_textid\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : \"commentInsert.do\",\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tsuccess : function() {\r\n");
      out.write("\t\t\t\talert(\"댓글이 등록되었습니다.\");\r\n");
      out.write("\t\t\t\tlistReply(\"1\");\r\n");
      out.write("\t\t\t}/* ,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\terror: function(req, status, errThrown) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"network error occur\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/*댓글 리스트 불러오기  */\r\n");
      out.write("\tfunction listReply(num) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : \"getCommentList.do?q_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&curPage=\" + num,\r\n");
      out.write("\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t$(\"#listReply\").html(result); //listReply\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- <br> -->\r\n");
      out.write("\t<!-- 댓글 작성 란 -->\r\n");
      out.write("\t<!-- <div style=\"width: 700px; text-align: center\"> -->\r\n");
      out.write("\t<!--현재는 로그인을 해야만 보임  -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<!-- <textarea rows=\"5\" cols=\"80\" name=\"comt_content\" id=\"comt_content\"\r\n");
      out.write("\t\t\tplaceholder=\"댓글을 작성하세요\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<button type=\"button\" id=\"btnReply\">댓글 작성</button> -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h2>Q&A</h2>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<form id=\"form1\" name=\"form1\" method=\"post\" action=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>qna 게시글의 제목입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<textarea rows=\"4\" cols=\"80\" name=\"q_content\" id=\"q_content\"\r\n");
      out.write("\t\t\t\t\t\t\t\treadonly>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"q_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"btnList\">목록</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <div class=\"ui-group-buttons\">\r\n");
      out.write("\t\t\t\t<a href=\"http://www.jquery2dotnet.com\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\trole=\"button\"><span class=\"glyphicon glyphicon-pencil\"\r\n");
      out.write("\t\t\t\t\tstyle=\"padding-right: 4px;\"></span>Compose</a>\r\n");
      out.write("\t\t\t\t<div class=\"or\"></div>\r\n");
      out.write("\t\t\t\t<a href=\"http://www.jquery2dotnet.com\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\trole=\"button\"><span class=\"glyphicon glyphicon-inbox\"\r\n");
      out.write("\t\t\t\t\tstyle=\"padding-right: 4px;\"></span>Inbox</a>\r\n");
      out.write("\t\t\t\t<div class=\"or\"></div>\r\n");
      out.write("\t\t\t\t<a href=\"http://www.jquery2dotnet.com\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\trole=\"button\"><span class=\"glyphicon glyphicon-send\"\r\n");
      out.write("\t\t\t\t\tstyle=\"padding-right: 4px;\"></span>Send</a>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"panel panel-default widget\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-comment\"></span>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"panel-title\">Comment</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--WRITE-->\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"btnReply\" class=\"[ btn btn-info ]\"\r\n");
      out.write("\t\t\t\t\tdata-loading-text=\"Loading...\">Post reply</button>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Write in your wall\" autofocus=\"\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ajax로 불러온 댓글 -->\r\n");
      out.write("\t\t\t\t<!-- \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<div id=\"listReply\"></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--REPLY-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2 col-md-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"http://placehold.it/80\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img-circle img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-10 col-md-11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\"> Congratulations</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tBy: <a href=\"#\">Check My Athletics</a> on 12 Jun 2014\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-text\">We would like to congratulate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tJohn on his achievement...</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2 col-md-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"http://placehold.it/80\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img-circle img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-10 col-md-11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\"> Congratulations</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tBy: <a href=\"#\">Check My Athletics</a> on 12 Jun 2014\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-text\">We would like to congratulate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tJohn on his achievement...</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 댓글 목록 출력 영역 -->\r\n");
      out.write("\t<!-- <div id=\"listReply\"></div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent(null);
    // /WEB-INF/views/qnaRead3.jsp(320,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qna.q_date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/qnaRead3.jsp(320,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/qnaRead3.jsp(363,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.m_email == qna.q_writer}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<button type=\"button\" id=\"btnUpdate\">수정</button>\r\n");
        out.write("\t\t\t\t\t\t<button type=\"button\" id=\"btnDelete\">삭제</button>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
