/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2019-09-06 17:23:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listBusinessMemberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/SpringMVCProject/Springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/8.29home/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1567346802003L));
    _jspx_dependants.put("jar:file:/D:/SpringMVCProject/Springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/8.29home/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"https://static.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico\" />\r\n");
      out.write("<link rel=\"mask-icon\" type=\"\"\r\n");
      out.write("\thref=\"https://static.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg\"\r\n");
      out.write("\tcolor=\"#111\" />\r\n");
      out.write("<title>회원목록</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tpadding: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("\tfont-family: \"Roboto\";\r\n");
      out.write("\tfont-weight: 500;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #aeaeae;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("\tmargin-bottom: 16px;\r\n");
      out.write("\tborder: 1px solid #eaeaea;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border-card {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tfont-family: \"Roboto\";\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder: 1px solid #eaeaea;\r\n");
      out.write("\tbox-shadow: 0px 2px 1px 0px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\ttransition: all 0.25s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border-card:hover {\r\n");
      out.write("\t-webkit-transform: translateY(-1px);\r\n");
      out.write("\ttransform: translateY(-1px);\r\n");
      out.write("\tbox-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.1), 0 5px 10px 0\r\n");
      out.write("\t\trgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border-card.over {\r\n");
      out.write("\tbackground: rgba(70, 222, 151, 0.15);\r\n");
      out.write("\tpadding-top: 24px;\r\n");
      out.write("\tpadding-bottom: 24px;\r\n");
      out.write("\tborder: 2px solid #47DE97;\r\n");
      out.write("\tbox-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0), 0 5px 10px 0 rgba(0, 0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border-card.over .card-type-icon {\r\n");
      out.write("\tcolor: #47DE97 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border-card.over p {\r\n");
      out.write("\tcolor: #47DE97 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-wrapper {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: flex-start;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttransition: all 0.25s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".min-gap {\r\n");
      out.write("\tflex: 0 0 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-type-icon {\r\n");
      out.write("\tflex-grow: 0;\r\n");
      out.write("\tflex-shrink: 0;\r\n");
      out.write("\tmargin-right: 16px;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tcolor: #323232;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttransition: all 0.25s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-type-icon.with-border {\r\n");
      out.write("\tcolor: #aeaeae;\r\n");
      out.write("\tborder: 1px solid #eaeaea;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-type-icon i {\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label-group {\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label-group.fixed {\r\n");
      out.write("\tflex-shrink: 0;\r\n");
      out.write("\twidth: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label-group p {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tline-height: 21px;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label-group p.title {\r\n");
      out.write("\tcolor: #323232;\r\n");
      out.write("\tfont-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label-group p.title.cta {\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label-group p.caption {\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tcolor: #aeaeae;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".end-icon {\r\n");
      out.write("\tmargin-left: 16px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\twindow.console = window.console || function(t) {\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tif (document.location.search.match(/type=embed/gi)) {\r\n");
      out.write("\t\twindow.parent.postMessage(\"resize\", \"*\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body translate=\"no\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<h2>List Business Information</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div class=\"alert alert-info\">\r\n");
      out.write("\t\t<strong>Total List Business Member Count : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("\t<div class=\"border-card\">\r\n");
      out.write("\t\t<div class=\"card-type-icon with-border\">1</div>\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"label-group fixed\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">EG links</p>\r\n");
      out.write("\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"\" id=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Einheit</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">Test</p>\r\n");
      out.write("\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"\" id=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Eigentümer</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">Alexander Oemisch</p>\r\n");
      out.write("\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"\" id=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Mieter</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group fixed\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">EG links</p>\r\n");
      out.write("\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"\" id=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Einheit</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">Test</p>\r\n");
      out.write("\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"\" id=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Eigentümer</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">Alexander Oemisch</p>\r\n");
      out.write("\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"\" id=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Mieter</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">Alexander Oemisch</p>\r\n");
      out.write("\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"\" id=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Mieter</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<i class=\"material-icons end-icon\">more_vert</i>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t<!--회원 리스트  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t<!-- <div class=\"border-card\">\r\n");
      out.write("\t\t<div class=\"card-type-icon with-border\">1</div>\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"label-group fixed\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">EG links</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Einheit</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">Marc-Philipp Weber</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Eigentümer</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"min-gap\"></div>\r\n");
      out.write("\t\t\t<div class=\"label-group\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">Alexander Oemisch</p>\r\n");
      out.write("\t\t\t\t<p class=\"caption\">Mieter</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<i class=\"material-icons end-icon\">more_vert</i>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<!-- <h4>Card with one information</h4>\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"border-card\" draggable=true>\r\n");
      out.write("<div class=\"card-type-icon with-border\"><i class=\"material-icons\">insert_drive_file</i></div>\r\n");
      out.write("<div class=\"content-wrapper\">\r\n");
      out.write("<div class=\"label-group\">\r\n");
      out.write("<p class=\"title\">Einladung zur Eigentümerversammlung</p>\r\n");
      out.write("<p class=\"caption\">Dokument</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<i class=\"material-icons\">more_vert</i>\r\n");
      out.write("</div>\r\n");
      out.write("<h4>Call-To-Action Card (try dragging a file over it)</h4>\r\n");
      out.write("<hr> -->\r\n");
      out.write("\t<!-- <div class=\"border-card droppable\">\r\n");
      out.write("<div class=\"card-type-icon\"><i class=\"material-icons\">cloud_upload</i></div>\r\n");
      out.write("<div class=\"content-wrapper\">\r\n");
      out.write("<div class=\"label-group\">\r\n");
      out.write("<p class=\"title cta\">Wartungsvertrag hochladen</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div> -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://static.codepen.io/assets/common/stopExecutionOnTimeout-de7e2ef6bfefd24b79a3f68b414b87b8db5b08439cac3f1012092b2290c719cd.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>\r\n");
      out.write("\t<script id=\"rendered-js\">\r\n");
      out.write("\t\t$('.droppable').bind('dragover', function(e) {\r\n");
      out.write("\t\t\t$(this).addClass('over');\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (e.originalEvent.preventDefault)\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\te.originalEvent.dataTransfer.dropEffect = 'copy';\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('.droppable').bind('dragenter', function(e) {\r\n");
      out.write("\t\t\t$(this).addClass('over');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('.droppable').bind('dragleave', function(e) {\r\n");
      out.write("\t\t\t$(this).removeClass('over');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('.droppable').bind('drop', function(e) {\r\n");
      out.write("\t\t\t$(this).removeClass('over');\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (e.originalEvent.stopPropagation)\r\n");
      out.write("\t\t\t\te.originalEvent.stopPropagation();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar stuff = $(e.originalEvent.dataTransfer.getData('stuff'));\r\n");
      out.write("\t\t\tstuff.appendTo(this);\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//# sourceURL=pen.js\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/member/listBusinessMemberList.jsp(249,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/listBusinessMemberList.jsp(249,1) '${list}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/member/listBusinessMemberList.jsp(249,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("row");
    // /WEB-INF/views/member/listBusinessMemberList.jsp(249,1) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("i");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t");
          out.write("\r\n");
          out.write("\t\t<div class=\"border-card\">\r\n");
          out.write("\t\t\t<div class=\"card-type-icon with-border\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count - i.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"content-wrapper\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"label-group fixed\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.m_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">E-mail</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 5%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.m_lname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.m_fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">Name</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 10%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.m_hp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">H.P.</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 20%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.m_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">Address</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 5%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.m_nation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">Nation</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 5%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">List Business</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">Type</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 5%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.b_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">Co. Name</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 10%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.b_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">Corporate Num</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\t\t\t\t<div class=\"label-group\" style=\"width: 10%;\">\r\n");
          out.write("\t\t\t\t\t<p class=\"title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.m_joindate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t<p class=\"caption\">Join Date</p>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<div class=\"min-gap\"></div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<i class=\"material-icons end-icon\">more_vert</i>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
