/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2019-08-23 03:11:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnaListIncomplete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 3 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 4 버전 -->\r\n");
      out.write("<!-- <link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" \r\n");
      out.write("\t\tintegrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("thead {\r\n");
      out.write("\tbackground-color: #ADD8E6;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.number_dot:after {\r\n");
      out.write("        content: \". \";\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("      }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 네비게이션 바~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  -->\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"#\">PayLog</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<ul class=\"nav navbar-nav \">\r\n");
      out.write("\t\t<li class=\"active\"><a href=\"#\">개인</a></li>\r\n");
      out.write("\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\" href=\"#\">구매 <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">모바일 구매</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">온라인 구매</a></li>\r\n");
      out.write("\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li><a href=\"#\">카드</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span>\r\n");
      out.write("\t\t\t\tSign Up</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span>\r\n");
      out.write("\t\t\t\tLogin</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--qna list table~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 완료, 미완료 구분 버튼 ===================================================================== -->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t <div class=\"btn-toolbar\">\r\n");
      out.write("\t\t<button class=\"btn btn-primary\">New User</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<button class=\"btn disabled\">\r\n");
      out.write("\t\t\t<strong>Complete</strong>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<button class=\"btn\">\r\n");
      out.write("\t\t\t<strong>Incomplete</strong>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h2>Q&A</h2>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t<li ><a href=\"#\">Complete</a></li>\r\n");
      out.write("\t\t<li class=\"active\"><a href=\"#\">Incomplete</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 테이블 리스트 =============================================================================== -->\r\n");
      out.write("\t<div class=\"well\">\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 70px\">No.</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 150px\">Division</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 670px\">Title</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 180px\">Writer</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 160px\">Date</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 60px\">check</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<td class=\"number_dot\">1</td>\r\n");
      out.write("\t\t\t\t\t<td>Mark</td>\r\n");
      out.write("\t\t\t\t\t<td>Tompson</td>\r\n");
      out.write("\t\t\t\t\t<td>the_mark7</td>\r\n");
      out.write("\t\t\t\t\t<td>the_mark7</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t<td>Ashley</td>\r\n");
      out.write("\t\t\t\t\t<td>Jacobs</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-ok\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t<td>Audrey</td>\r\n");
      out.write("\t\t\t\t\t<td>Ann</td>\r\n");
      out.write("\t\t\t\t\t<td>audann84</td>\r\n");
      out.write("\t\t\t\t\t<td>audann84</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>4</td>\r\n");
      out.write("\t\t\t\t\t<td>John</td>\r\n");
      out.write("\t\t\t\t\t<td>Robinson</td>\r\n");
      out.write("\t\t\t\t\t<td>jr5527</td>\r\n");
      out.write("\t\t\t\t\t<td>jr5527</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t<td>Aaron</td>\r\n");
      out.write("\t\t\t\t\t<td>Butler</td>\r\n");
      out.write("\t\t\t\t\t<td>aaron_butler</td>\r\n");
      out.write("\t\t\t\t\t<td>aaron_butler</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>6</td>\r\n");
      out.write("\t\t\t\t\t<td>Chris</td>\r\n");
      out.write("\t\t\t\t\t<td>Albert</td>\r\n");
      out.write("\t\t\t\t\t<td>cab79</td>\r\n");
      out.write("\t\t\t\t\t<td>cab79</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>7</td>\r\n");
      out.write("\t\t\t\t\t<td>Ashley</td>\r\n");
      out.write("\t\t\t\t\t<td>Jacobs</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>8</td>\r\n");
      out.write("\t\t\t\t\t<td>Aaron</td>\r\n");
      out.write("\t\t\t\t\t<td>Butler</td>\r\n");
      out.write("\t\t\t\t\t<td>aaron_butler</td>\r\n");
      out.write("\t\t\t\t\t<td>aaron_butler</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>9</td>\r\n");
      out.write("\t\t\t\t\t<td>Ashley</td>\r\n");
      out.write("\t\t\t\t\t<td>Jacobs</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t<td>Audrey</td>\r\n");
      out.write("\t\t\t\t\t<td>Ann</td>\r\n");
      out.write("\t\t\t\t\t<td>audann84</td>\r\n");
      out.write("\t\t\t\t\t<td>audann84</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>11</td>\r\n");
      out.write("\t\t\t\t\t<td>John</td>\r\n");
      out.write("\t\t\t\t\t<td>Robinson</td>\r\n");
      out.write("\t\t\t\t\t<td>jr5527</td>\r\n");
      out.write("\t\t\t\t\t<td>jr5527</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"user.html\"><span class=\"glyphicon glyphicon-pencil\"></span></a> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <i class=\"icon-ok\"></i> <a href=\"user.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a> -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\" align=\"center\">\r\n");
      out.write("\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">Prev</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Next</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 페이지네이션~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("\t<!-- <div class=\"pagination\" align=\"center\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Prev</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Next</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal small hide fade\" id=\"myModal\" tabindex=\"-1\"\r\n");
      out.write("\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-header\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\taria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t<h3 id=\"myModalLabel\">Delete Confirmation</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal-body\">\r\n");
      out.write("\t\t<p class=\"error-text\">Are you sure you want to delete the user?</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t<button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">Cancel</button>\r\n");
      out.write("\t\t<button class=\"btn btn-danger\" data-dismiss=\"modal\">Delete</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
