/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2019-08-23 03:06:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnaList_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("\t.navbar-nav.navbar-center {\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 50%;\r\n");
      out.write("\t\ttransform: translatex(-50%);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.ico\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("<title>Awesome Landing Page by Creative Tim</title>\r\n");
      out.write("<meta\r\n");
      out.write("\tcontent='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'\r\n");
      out.write("\tname='viewport' />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/landing-page.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!--     Fonts and icons     -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/pe-icon-7-stroke.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- body\\==================================================================== -->\r\n");
      out.write("<body class=\"landing-page landing-page1\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 네비게이션 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- <nav class=\"navbar navbar-transparent navbar-fixed-top\" role=\"navigation\"> -->\r\n");
      out.write("\t<nav class=\"navbar navbar-dark bg-warning\">\r\n");
      out.write("\t<div class=\"navbar-header navbar-dark\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\r\n");
      out.write("\t\t<ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">PayLog</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">개인</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">고객</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">구매</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">로그인</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!--AJAX 처리  -->\r\n");
      out.write("\t<div class=\"btn-toolbar\">\r\n");
      out.write("\t\t<button class=\"btn btn-primary\">답변 완료</button>\r\n");
      out.write("\t\t<button class=\"btn\">답변 미완료</button>\r\n");
      out.write("\t\t<button class=\"btn\">시간 정렬</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"well\">\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t<th>답변 여부</th>\r\n");
      out.write("\t\t\t\t\t<th>구분</th>\r\n");
      out.write("\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t<th>등록일</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 36px;\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t<td>Mark</td>\r\n");
      out.write("\t\t\t\t\t<td>Tompson</td>\r\n");
      out.write("\t\t\t\t\t<td>the_mark7</td>\r\n");
      out.write("\t\t\t\t\t<td>the_mark7</td>\r\n");
      out.write("\t\t\t\t\t<td>the_mark7</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"user.html\"><i class=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t<td>Ashley</td>\r\n");
      out.write("\t\t\t\t\t<td>Jacobs</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td>ash11927</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"user.html\"><i class=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t<td>Audrey</td>\r\n");
      out.write("\t\t\t\t\t<td>Ann</td>\r\n");
      out.write("\t\t\t\t\t<td>audann84</td>\r\n");
      out.write("\t\t\t\t\t<td>audann84</td>\r\n");
      out.write("\t\t\t\t\t<td>audann84</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"user.html\"><i class=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>4</td>\r\n");
      out.write("\t\t\t\t\t<td>John</td>\r\n");
      out.write("\t\t\t\t\t<td>Robinson</td>\r\n");
      out.write("\t\t\t\t\t<td>jr5527</td>\r\n");
      out.write("\t\t\t\t\t<td>jr5527</td>\r\n");
      out.write("\t\t\t\t\t<td>jr5527</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"user.html\"><i class=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t<td>Aaron</td>\r\n");
      out.write("\t\t\t\t\t<td>Butler</td>\r\n");
      out.write("\t\t\t\t\t<td>aaron_butler</td>\r\n");
      out.write("\t\t\t\t\t<td>aaron_butler</td>\r\n");
      out.write("\t\t\t\t\t<td>aaron_butler</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"user.html\"><i class=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>6</td>\r\n");
      out.write("\t\t\t\t\t<td>Chris</td>\r\n");
      out.write("\t\t\t\t\t<td>Albert</td>\r\n");
      out.write("\t\t\t\t\t<td>cab79</td>\r\n");
      out.write("\t\t\t\t\t<td>cab79</td>\r\n");
      out.write("\t\t\t\t\t<td>cab79</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"user.html\"><i class=\"icon-pencil\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#myModal\" role=\"button\" data-toggle=\"modal\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-remove\"></i></a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">Prev</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--페이지네이션 bs 4  ===========================================================================================-->\r\n");
      out.write("\t<!-- <div class=\"pagination\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Prev</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Next</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal small hide fade\" id=\"myModal\" tabindex=\"-1\"\r\n");
      out.write("\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\taria-hidden=\"true\">Ã</button>\r\n");
      out.write("\t\t\t<h3 id=\"myModalLabel\">Delete Confirmation</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t<p class=\"error-text\">Are you sure you want to delete the user?</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t<button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">Cancel</button>\r\n");
      out.write("\t\t\t<button class=\"btn btn-danger\" data-dismiss=\"modal\">Delete</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
